name: Execute On Push

on:
  workflow_dispatch:

jobs:

  delete-history:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Execute On Push
      run: |
        git checkout --orphan latest_branch
        git config user.email "github-actions@users.noreply.github.com"
        git config user.name "GitHub Actions"
        git add -A
        git commit -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z') 🌿"
        git branch -D dev
        git branch -m dev
        git push -f origin dev
